server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Pure-Chan/springclloud2021.git #GitHub上面的git仓库名字
          #####搜索目录
          search-paths:
            - springclloud2021
          username: Pure-Chan
          password: 2422941941cjx
          force-pull: true
      #######读取分支
      label: master

####服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka